export const datass = [
    {
        uri : require('../assets/images/Planetsimage/Sun.jpg'),
        name : 'Sun',
        para:'The Sun, a colossal ball  of hot plasma at the center of our solar system, is a G-type main-sequence star (G2V) that sustains life on Earth. It generates energy through nuclear fusion in its core, converting hydrogen into helium and releasing an immense amount of heat and light. With a diameter of about 1.39 million kilometers, the Sun is approximately 109 times wider than Earth. Its gravitational pull governs the orbits of all the planets, asteroids, and comets in our solar system. The Suns activity, including solar flares and sunspots, influences space weather and can impact satellite communications and power grids on Earth. Its energy output, primarily in the form of visible light, ultraviolet light, and infrared radiation, is crucial for driving Earths climate and weather systems.'
    },
    {
        uri : require('../assets/images/Planetsimage/Mercury.jpg'),
        name : 'Mercury',
        para : 'Almost twice this of Pluto and 4879 km in diameter, Mercury is the closest planet to the Sun at a distance of only 57.9 million kilometres. It is the only 5% of earth size and takes 58.65 days to revolve around on its axis which mean that it has a day of which equal to 180 Earth days. Like Venus, Mercury does not have any moon: Mercury has the highest orbital velocity because of which it takes only 88 days to complete one revolution around the Sun. The surface gravity is about 40% of Earths gravity. Some of the first picture taken by the space probe Mariner 10 showed that Mercury has a rocky terrain where the surface temperature rose as high as 350 degrees centigrade. The appearance of Mercury are known as elongations which comes at intervals of 116 days, in other words Mercury can be seen thrice the year. Mercury last passed in front of the sun on the 13th November 1986.'
    },
    {
        uri : require('../assets/images/Planetsimage/Venus.jpg'),
        name : 'Venus',
        para : 'Next to Mercury, Venus is the hottest and the brightest planet in the Suns family. Venus has a diameter of 12,104 kilometres and is located 108 million kilometres from the Sun. It has a surface gravity of 0.90 as compared to Earth. Venus rotates on its axis in a clockwise direction in 243.16 days thus having a four-year day. It travels at a speed of 35 kilometre per second and it takes about 225 days to orbit the Sun once. Beside Mercury, Venus is the only planet in our Solar System which does not have any moons. The atmosphere Solar of Venus is about 90 times thicker than ours and compared largely of carbon dioxide and clouds. The rays of the Sun are absorved by the planets surface and both the carbon dioxide and the clouds around the planet do not allow the heat to escape thus causing the greenhouse effect which results in temperature as high as 480 degree centigrade.'
    },
    {
        uri : require('../assets/images/Planetsimage/EarthImage.jpg'),
        name : 'Earth',
        para : 'Our planet earth is a part of sons family and is located about 150 million kilometre away from it. The sun has formed due to construction of cloud of gases and dust the remaining out of this cloud eventually formed the other planets in the same manner. The earth to close 200 million years to become a glowing ball comprising of molten rock. The molten rocks on the surface gradually began to sink towards the centre as the result of this crust was formed. Volcanoes on the surface regularly throughout this molten Rock and other gases. These gases in turn formed water vapours and the layer of atmosphere which surrounds the earth. The earth as we see it today has a diameter of 10756 and the circumference of 40075 kilometre at the equator it has a total mass of about 6 billion billion tons which a land area almost 29% the balance 71% areas covered by the ocean. Just like a globe on its imaginary axis and it takes 23 hours 59 minutes 14 seconds to complete one rotation causing day and night. Like The Other planets the earth also revolves around the sun and it takes 365 days 6 hours in 9 minutes to complete one revolution. The earth is tilted on its Axis at an angle of 23.5 degrees it is because of the tree that the suns rays fall and can easily on different parts of the earth was giving us different Seasons the amount of time the Earth takes to revolve on its Axis decides Knight and day for a and the earth taken is going around the sun once given us the year.'
    },
    {
        uri : require('../assets/images/Planetsimage/Mars.jpg'),
        name : 'Mars',
        para : 'Mars the, fourth planet has a diameter of 6,794 kilometres and it orbits at a distance of 228 million kilometres from the Sun. The surface gravity on Mars is 0.38 of the Earths gravity and the planet is about one tenth the size of Earth. Mars moves at a speed of 24 km per second and takes about 780 days to complete one revolution around the Sun. One rotation on its axis is completed in about 24 hours and 37 minutes. It has to moon called Phobes which is 23 kilometre in diameter and Demos which is 13 kilometres in diameter. Since it is relatively closer to the sun as compared to the other outer planets, the surface temperature ranges from - 9 degree to minus 23 degree centigrade. In the earlier centuries the astronomers believe that Mars was very much like Earth. The first photograph of Mars but taken by the Mariner 4 spacecraft in the year 1965, subsequently Mariner 8 took some in the year 1971. As a result of these pictures it was discovered that the surface of the planet has red in colour, Rocky and dry. In 1976 two unmanned Viking spacecraft were sent to this planets. The data sent back by the spacecraft showed and absence of carbon atom and living organisms in the atmosphere and soil. From this finding the scientist concluded that there would be no life on Mars and that it was a dead planet. Mars has a red colour because of two reasons firstly the soil and rocks are largely composed of iron which has rusted due to exposure of weather has giving them a reddish appearance secondly the entire surface is covered with a fine dust which hangs in the air as a result of which the sky tend to have a reddish colour rather than the usual blue. Mars has to polar caps both of which are frozen and covered with ice. Also have a number of volcanoes and valleys which indicates that there may have been or there may still be geological activity on this planet.'
    },
    {
        uri : require('../assets/images/Planetsimage/Jupiter.jpg'),
        name : 'Jupiter',
        para : 'Jupiter is largely made up of liquids gases and sling cloud of hydrogen and helium. These liquids are gases become denser and denser as we move towards the planet centre. Jupiter the largest planet in the solar system with a diameter 142884 kilometres which is 318 times that of Earth besides this it also known the fastest spinning planet it take only 9 hours and 15 minutes to complete one rotation. Different parts of its surface rotate at different times as an example the large red spot on Jupiter surface tension extra 5 to 7 minutes to rotate similarly the over white cloud on its surface have a different speed of its own. The central or Collateral region of Jupiter Bubbles outward bio about 5000 as a result of the centrifugal force. It is a cold planet with temperature as low as - 150 degree centigrade. In Orbit at 778 million kilometres from the sun Jupiter at a speed of 13.1 metre per second takes 11.8 5 years to revolve on its path around the sun. Jupiter is more like a miniature solar system on its own since it has 16 moon some of which are very large as and among these the smallest morning only about 15 kilometre or lessen the diameter the Moons were discovered by Galileo Galilei and he had then called the four bright moon is or at the American stars. The surface gravity on the planet is 2.64 times that of earth the first spacecraft to fly past Jupiter in 1973 was the Pioneer eggs followed by the Pioneer 11 in the year 1979 and subsequently the Voyager 1 and watch your 2. Jupiter has shown as pattern of changing its colour overtime to beds on on the outer surface changes colour from red to brown to grey and then at time to glue the this effect occurs 112 years from the 7th of July 1994 convert Jupiter has bombarded by 19 piece of comet Soma Karli V which was on a collision course with this planet. Each of the collision generate heat in excess of 30000 centigrade and an explosion in excess of 13000 billion megaton of TNT and left scar on the surface of Jupiter.',
    },
    {
        uri : require('../assets/images/Planetsimage/Saturn.jpeg'),
        name : 'Saturn',
        para : 'Saturn is the sixth planet in order of revolution in the family of the Sun. It has a diameter of 120526 KM and is located in Orbit about 1427 million kilometres away from the sun. Saturn is about 95 time larger and has a surface gravity of 1.16 as compared to earth moving at speed of 9.6 metre per second it take about 30 years to complete one Revolution around the sun and take 10 hours and 39 minutes to complete one rotation on its axis full stop it has 23 moon which revolve on around it because of its distance from the sun Saturn is a cold planet and temperature on the surface vary from - 180 degree 2 - 292 degree centigrade Saturn is one of the four planet which has rings around it has shown in the illustration these rings made up of million of fragments of rob coated with eyes surrounded this distant planet it is not confirmed how is ringworm form but it is assumed that the Rings are frequented of moon which broke apart and was suspended around the planet millions of years ago. Saturn rings are about 22 time bigger than Earth diameter they are however only the few kilometres think some of the Rings have a larger number of frozen doc clusters as a result of which more light get reflected which in turn explain why the Rings are the different colours for stop one of the moon circling this planet is the largest satellite known to man it is the moon called Titan. It has a diameter of 5120 and is bigger than both Pluto and mercury Saturn is the second fastest rotating planet next to Jupiter it is the only last few decades that need to know a lot about Saturn. This was made possible through visits to Saturn by unmanned spacecraft sent by Earth. Saturn has first visit by young man Pioneer 11 space probe in 1979 and subsequently in 1986 by the Voyager 1 and watch your to space force. Both the Space Pro stand back invaluable pictures of the planet.'
    },
    {
        uri : require('../assets/images/Planetsimage/Uranus.jpg'),
        name : 'Uranus',
        para : 'Uranus was discovered by William herschel in the year 1781 for stock Harshita build the largest school is scope of that a go to do so first of located about 2819 million km from the Sun Yunus is the seventh planet in our solar system. 3rd largest in size penis has a diameter of 51118 kilometres and it is about fifteen times to size of earth has a surface gravity of only two 0.93 as compared to earth unit 1 17 hours to skin on its axis and about eighty four years to complete one Revolution around the sun Uranus has the solid core made up of metal which is surrounded by eyes and gases like Hydrogen and methane helium is it true or false top the surface temperatures as low as - 214 degree centigrade beside Venus universe is the only planet which does not rotate by the other planets in solar system it is tilted and it rotates on its side us has its own family which comprises of 15 month.'
    },
    {
        uri : require('../assets/images/Planetsimage/Neptune.jpg'),
        name : 'Neptune',
        para : 'Neptune was the first planet to be discovered by using mathematics. After the discovery of Uranus in 1781, astronomers noticed that the planet was being pulled slightly out of its normal orbit. John Couch Adams of Britain and Urbain Jean Joseph Leverrier of France, used mathematics to predict that the gravity from another planet beyond Uranus was affecting the orbit of Uranus. They figured out not only where the planet was, but also how much mass it had. A young astronomer, Johann Gottfried Galle, decided to search for the predicted planet and observed Neptune for the first time in 1846. A planets day is the time it takes the planet to rotate or spin once on its axis. Neptune rotates faster than Earth so a day on Neptune is shorter than a day on Earth. A day on Neptune is about 16 Earth hours while a day on Earth is 23.934 hours. The average distance of Neptune from the Sun is 2,795,084,800 miles or 4,498,252,900 kilometers. Because its orbit is elliptical, its distance from the Sun changes depending on where it is in its orbit. The closest Neptune gets to the Sun is 2,771,087,000 miles or 4,459,630,000 kilometers. The farthest it gets from the Sun is 2,819,080,000 miles or 4,536,870,000 kilometers. The surface gravity on Neptune is about 110% of the surface gravity on Earth, so if you weigh 100 pounds on Earth, you would weigh 110 pounds on Neptune (assuming you could find someplace to, well, stand). Neptune has thirteen moons that we know of with one more waiting for confirmation. The largest moon is Triton. Triton is slightly smaller than Earths Moon and has active volcanoes which erupt like geysers and eject nitrogen frost over the surface. Some of the other moons of Neptune are Nereid, Proteus, Larissa, Despina, Galatea, Thalassa, and Naiad. These moons are much smaller than Triton and, except for Nereid, were not discovered until the Voyager spacecraft flew by them in 1989. With better telescope we are sure to discover more moons around Neptune.'
    }
]